# Generated by Django 5.2.4 on 2025-08-07 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_disaster_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_needed', models.CharField(max_length=50)),
                ('water_required', models.CharField(max_length=50)),
                ('Volunteers_required', models.CharField(max_length=50)),
                ('medical_kits', models.CharField(max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shelter')),
            ],
        ),
    ]
