# Generated by Django 5.2.4 on 2025-08-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_predictedvalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedvalues',
            name='Volunteers_required',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='predictedvalues',
            name='food_needed',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='predictedvalues',
            name='medical_kits',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='predictedvalues',
            name='water_required',
            field=models.IntegerField(max_length=50),
        ),
    ]
