# Generated by Django 5.2.4 on 2025-08-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_predictedvalues_volunteers_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictedvalues',
            name='Volunteers_required',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictedvalues',
            name='food_needed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictedvalues',
            name='medical_kits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictedvalues',
            name='water_required',
            field=models.IntegerField(),
        ),
    ]
