# Generated by Django 5.2.4 on 2025-08-11 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_predictedvalues_volunteers_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='type',
            field=models.CharField(choices=[('Fire', 'Fire'), ('Flood', 'Flood'), ('Earthquake', 'Earthquake'), ('Storm/Hurricane', 'Storm'), ('Tornado', 'Tornado'), ('Landslide', 'Landslide'), ('Tsunami', 'Tsunami'), ('Volcanic Eruption', 'Volcanic Eruption'), ('Drought', 'Drought'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='predictedvalues',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.shelter'),
        ),
    ]
