# Generated by Django 5.2.4 on 2025-08-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_disaster_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='type',
            field=models.CharField(choices=[('Fire', 'Fire'), ('Flood', 'Flood'), ('Earthquake', 'Earthquake'), ('Storm/Hurricane', 'Storm/Hurricane'), ('Tornado', 'Tornado'), ('Landslide', 'Landslide'), ('Tsunami', 'Tsunami'), ('Volcanic Eruption', 'Volcanic Eruption'), ('Drought', 'Drought'), ('Other', 'Other')], max_length=20),
        ),
    ]
