# Generated by Django 6.0.1 on 2026-01-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_disaster_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disaster',
            name='image',
        ),
        migrations.AddField(
            model_name='disaster',
            name='display_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ShelterImage',
        ),
    ]
